### ISSUE TITLE
 error: need more than 2 values to unpack

### ISSUE THREAD

**Issue by amahlaka** [davidmroth/AlexaPi#2]
after starting alexa, logs show this:
```
ERROR - error: need more than 2 values to unpack
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 164, in __synchronize_state
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack

```

**Comment by davidmroth** [comment]
My guess is you don't have something configured correctly.  Look at this line (/opt/AlexaPi/src/alexa/http/http.py, line 164):

`request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)`

**Comment by davidmroth** [comment]
Add a print statement to: full_url & headers before line 164 and post the output:

`
print full_url`
`print headers
`

**Comment by amahlaka** [comment]
```
- ERROR - <function <lambda> at 0x751fe8b0>(): Could not open AVS downchannel stream - https://avs-alexa-na.amazon.com/v20160207/directives
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 146, in __open_downchannel_stream
    response = self.__session.get(full_url, headers=headers, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-11-24 19:54:39,376 - alexa.http.http - ERROR - error: need more than 2 values to unpack
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 146, in __open_downchannel_stream
    response = self.__session.get(full_url, headers=headers, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-11-24 19:54:39,513 - alexa.http.http - ERROR - <function <lambda> at 0x751fe8b0>(): Could not synchronize state - %s
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 164, in __synchronize_state
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-11-24 19:54:39,522 - alexa.http.http - ERROR - error: need more than 2 values to unpack
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 164, in __synchronize_state
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-11-24 19:54:51,666 - alexa.http.http - ERROR - <function <lambda> at 0x751fe8b0>(): Could not post to: https://avs-alexa-na.amazon.com/v20160207/events/
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 191, in post
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 78, in send
    request.headers
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 103, in request
    method=method, url=url, body=body, headers=headers
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 183, in request
    self._send_headers(method, url, headers)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 228, in _send_headers
    self._sock.send(b' '.join([method, url, b'HTTP/1.1\r\n']))
  File "/usr/lib/python2.7/ssl.py", line 667, in send
    v = self._sslobj.write(data)
error: [Errno 32] Broken pipe
2016-11-24 19:54:51,670 - alexa.http.http - ERROR - error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 191, in post
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 78, in send
    request.headers
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 103, in request
    method=method, url=url, body=body, headers=headers
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 183, in request
    self._send_headers(method, url, headers)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 228, in _send_headers
    self._sock.send(b' '.join([method, url, b'HTTP/1.1\r\n']))
  File "/usr/lib/python2.7/ssl.py", line 667, in send
    v = self._sslobj.write(data)
error: [Errno 32] Broken pipe
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/alexa/avs/directive_dispatcher.py", line 76, in processor
    log.debug("{}(process_response Error){} Status Code: {} - {}".format(shared.bcolors.WARNING, shared.bcolors.ENDC, r.status_code, r.text))
AttributeError: 'bool' object has no attribute 'status_code'

```

**Comment by amahlaka** [comment]
```
https://avs-alexa-na.amazon.com/v20160207/events
{'Authorization': 'Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxrxxxxxxxxxxxxxxx'}
```

**Comment by davidmroth** [comment]
Can you enable logging? See the updated config file I posted in #1

**Comment by davidmroth** [comment]
BTW, just tested this branch, and its working for me. I'm still leaning towards a configuration error.

**Comment by scottdmoore** [comment]
I did a fresh install after seeing your comments to @amahlaka. I had master working earlier. I added your custom config options that were left out. I enabled debugging for everything

```
debug:
        alexa: 'debug'
        hpack: 'debug'
        hyper: 'debug'
        requests: 'debug'

alexa:
  API_Version: "v20160207"
  EventPath: "/events"
  AuthUrl: "https://api.amazon.com"
  BaseUrl: "https://avs-alexa-na.amazon.com"
```

Here are my logs including an added print statement to: full_url & headers before line 164

print full_url
print headers

```
pi@raspberrypi:/opt/AlexaPi $ sudo python src/main.py
2016-12-20 22:28:40,593 - alexa.http.http - INFO - Checking Internet Connection...
2016-12-20 22:28:40,595 - alexa.http.http - INFO - Connection OK
https://avs-alexa-na.amazon.com/v20160207/directives
{'Authorization': 'SECRET'}
2016-12-20 22:28:40,877 - hyper.http11.connection - DEBUG - Selected protocol: None
2016-12-20 22:28:40,878 - alexa.http.http - ERROR - <function <lambda> at 0x75264e30>(): Could not open AVS downchannel stream - https://avs-alexa-na.amazon.com/v20160207/directives
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 146, in __open_downchannel_stream
    response = self.__session.get(full_url, headers=headers, stream=True, timeout=None)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-12-20 22:28:40,881 - alexa.http.http - ERROR - error: need more than 2 values to unpack
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 146, in __open_downchannel_stream
    response = self.__session.get(full_url, headers=headers, stream=True, timeout=None)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-12-20 22:28:40,886 - alexa.http.http - ERROR - <function <lambda> at 0x75264e30>(): Could not synchronize state - %s
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 164, in __synchronize_state
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-12-20 22:28:40,887 - alexa.http.http - ERROR - error: need more than 2 values to unpack
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 164, in __synchronize_state
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
2016-12-20 22:28:41,488 - alexa.avs.interface_manager - INFO -
2016-12-20 22:28:41,489 - alexa.avs.interface_manager - INFO - ----------------------
2016-12-20 22:28:41,489 - alexa.avs.interface_manager - INFO - Importing alexa.avs.interface.SpeechRecognizer...
2016-12-20 22:28:41,491 - alexa.avs.interface_manager - INFO - Importing alexa.avs.interface.AudioPlayer...
2016-12-20 22:28:41,491 - alexa.avs.interface_manager - INFO - Importing alexa.avs.interface.SpeechSynthesizer...
2016-12-20 22:28:41,492 - alexa.avs.interface_manager - INFO - ----------------------
2016-12-20 22:28:41,492 - alexa.avs.interface_manager - INFO -
!! Traceback (most recent call last):
!!   File "src/main.py", line 220, in <module>
    setup()
!!   File "src/main.py", line 215, in setup
    avs_interface = InterfaceManager()
!!   File "/opt/AlexaPi/src/alexa/avs/interface_manager.py", line 27, in __init__
    self.__import_modules()
!!   File "/opt/AlexaPi/src/alexa/avs/interface_manager.py", line 57, in __import_modules
    interface_ref = getattr(mod, module, False)(self)
!! TypeError: 'bool' object is not callable

Exiting...
```

**Comment by scottdmoore** [comment]
I checked my version of hyper
```
pi@raspberrypi:/opt/AlexaPi $ hyper --version
0.7.0
```
And I tried commenting out open_downchannel_stream
```
pi@raspberrypi:/opt/AlexaPi $ sudo python src/main.py
2016-12-20 22:46:53,628 - alexa.http.http - INFO - Checking Internet Connection...
2016-12-20 22:46:53,630 - alexa.http.http - INFO - Connection OK
2016-12-20 22:46:53,948 - hyper.http11.connection - DEBUG - Selected protocol: None
2016-12-20 22:46:53,950 - alexa.http.http - ERROR - <function <lambda> at 0x752e6df0>(): Could not synchronize state - %s
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 166, in __synchronize_state
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 80, in send
    resp = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 204, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 2 values to unpack
```

**Comment by davidmroth** [comment]
@scottdmoore I can only assume at this point it has something to do with the distros you guys are using.  I am now running this code on my Intel Macbook Air 5,1 on Ubuntu 16.04 and I still don't see this problem.

Any thoughts you can share that may help resolve this issue would be greatly appreciated as I cannot reproduce on my hardware.

BTW, I have uploaded a massive update. I doubt it will fix the issues you guys are having, but it may be worth a shot.

**Comment by scottdmoore** [comment]
Maybe we have different versions of the hyper Python library. The version I sent you and the one you mentioned earlier was for the hyper command line utility not the Python library. What is your pip hyper version?

**Comment by davidmroth** [comment]
```
$ pip list | grep hyper
hyper (0.7.0)
hyperframe (3.2.0)
```

**Comment by davidmroth** [comment]
I checked with @amahlaka earlier. I thought the same, but it appears we are using the same version.

Do you have a PC with Ubuntu on it? I would be interested in seeing if you see the same issue on another distro.
